### ISSUE TITLE
Teams: registration form

### ISSUE THREAD

**Issue by uaoleg** [uaoleg/icpc.org.ua#344]
Need to implement generation of registration form for each team. It should be accessible for team's coach and coordinators as a button on team's page.

![image](https://cloud.githubusercontent.com/assets/1773775/7132530/d84fe6ea-e292-11e4-8713-9a8b1f1a3079.png)

**Comment by kirillmart** [comment]
No button is available on team's page. See screen
![1](https://cloud.githubusercontent.com/assets/6258298/7156683/54ea251a-e371-11e4-8c3f-c3d12e11962f.PNG)
