### ISSUE TITLE
In Students and Coaches tables, region coordinator can't see any user

### ISSUE THREAD

**Issue by kirillmart** [uaoleg/icpc.org.ua#360]
Scenario
1. Register new Coordinator
2. Login to system using his credentials
3. Go to Users - Students and USers - Coaches

Expected
Coordinator can see users

Actual
Coordinator can't see users. When trying to export table - 404 error is shown

![1](https://cloud.githubusercontent.com/assets/6258298/7249913/8bacc788-e826-11e4-9099-a21c83cadb0e.PNG)

**Comment by uaoleg** [comment]
Fixed
